### ISSUE TITLE
flights.flights2d SQL fails

### ISSUE THREAD

**Issue by matburnham** [glidernet/ogn-python#66]
Running `manage.py flights.flights2d` fails.

```
2019-02-15:   0%|                                                                                                               | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: syntax error at or near "simple_multilinestring"
LINE 12: ...ect(st_simplify(sq5.linestring ORDER BY sq5.part) simple_mul...
                                                              ^
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    manager.main()
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/manager/__init__.py", line 333, in main
    command.parse(args.all[1:])
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/manager/__init__.py", line 130, in parse
    r = self(*args, **kwargs)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/manager/__init__.py", line 62, in __call__
    return self.run(*args, **kwargs)
  File "/webapps/ogn/ogn-python/ogn/commands/flights.py", line 78, in flights2d
    result = compute_flights2d(session=session, date=single_date)
  File "/webapps/ogn/ogn-python/ogn/commands/flights.py", line 65, in compute_flights2d
    session.execute(query)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) syntax error at or near "simple_multilinestring"
LINE 12: ...ect(st_simplify(sq5.linestring ORDER BY sq5.part) simple_mul...
                                                              ^
 [SQL: "\n    INSERT INTO flights2d\n    (\n    date,\n    device_id,\n    path,\n    path_simple\n    )\n    SELECT   sq5.date,\n    sq5.device_id,\n    st_collect(sq5.linestring order BY sq5.part) multilinestring,\n    st_collect(st_simplify(sq5.linestring ORDER BY sq5.part) simple_multilinestring\n    FROM     (\n        SELECT   sq4.timestamp::date AS date,\n        sq4.device_id,\n        sq4.part,\n        st_makeline(sq4.location ORDER BY sq4.timestamp) linestring\n        FROM     (\n            SELECT   sq3.timestamp,\n            sq3.location,\n            sq3.device_id,\n            sum(sq3.ping) OVER (partition BY sq3.timestamp::date, sq3.device_id ORDER BY sq3.timestamp) part\n            FROM     (\n                SELECT sq2.t1 AS timestamp,\n                    sq2.l1 AS location,\n                    sq2.d1    device_id,\n                    CASE\n                        WHEN sq2.t1 - sq2.t2 < interval'100s' AND ST_DistanceSphere(sq2.l1, sq2.l2) < 1000 THEN 0\n                        ELSE 1\n                    END AS ping\n                FROM   (\n                    SELECT  sq.timestamp                                                             t1,\n                            lag(sq.timestamp) OVER (partition BY sq.device_id ORDER BY sq.timestamp) t2,\n                            sq.location                                                              l1,\n                            lag(sq.location) OVER (partition BY sq.device_id ORDER BY sq.timestamp)  l2,\n                            sq.device_id                                                             d1,\n                            lag(sq.device_id) OVER (partition BY sq.device_id ORDER BY sq.timestamp) d2\n                    FROM     (\n                        SELECT   DISTINCT ON (device_id, timestamp) timestamp, device_id, location\n                        FROM     aircraft_beacons\n                        WHERE    timestamp BETWEEN '2019-02-15 00:00:00' AND '2019-02-15 23:59:59'\n                        ORDER BY device_id, timestamp, error_count\n                    ) sq\n                ) sq2\n            ) sq3\n        ) sq4\n        GROUP BY sq4.timestamp::date, sq4.device_id, sq4.part\n    ) sq5\n    GROUP BY sq5.date, sq5.device_id\n    ON CONFLICT DO NOTHING;\n    "] (Background on this error at: http://sqlalche.me/e/f405)
```

Looking at [ogn/commands/flights.py](https://github.com/glidernet/ogn-python/blob/master/ogn/commands/flights.py) it looks like `st_simplify(sq5.linestring,` isn't complete. Changing it to `st_simplify(sq5.linestring, 10)` appears to fix it but I'm not sure what the simplify is trying to achieve so this may not be the correct tolerance value.

Untested (or only tested as far as valid SQL) as my next problem is all `device_id` are `null` in my `aircraft_beacons` table causing `sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) null value in column "device_id" violates not-null constraint`.

**Comment by Meisterschueler** [comment]
Shame on me! I am using bulkimport only, so I did not see the problems with the 'real time' import.

1) The missing parameter should be 0.0001. With the ST_Simplify command we are ignoring minimal position changes, e.g. while waiting in the grid.

2) Next problem: missing device_id. The bulk import update device_id and receiver_id for a complete day at once. The 'real time' import should keep the device_ids and receiver_ids and update all incoming beacons. This need a small modification on DbSaver.

3) I am currently working on the branch 'flask_integration', because I want to have a gui for the db. I will implement the fixes for 1) and 2) in the next days and then merge it into the trunk. Be aware: I dropped the current manage.py command structure and switched to 'flask click'.

**Comment by matburnham** [comment]
Ah, it's not just me being stupid and missing something then. That's good news. Half the trouble is knowing how it's supposed to work versus what I'm actually seeing. What's the use case for bulkimport versus real time?

It sounds like 2) would give me what I'm looking for. And a GUI to visualise the database in 3) would be super. Look forward to playing with that.

**Comment by Meisterschueler** [comment]
The use case for bulkimport is: you can just dump the aprs stream into a log file. These logfiles can be quite big. For several days in 2018 I have logfiles compressed > 1GB. If you import these files row by row then it is extreme slow.

The problem is: messages from aprs stream go into the tables aircraft_beacons and receiver_beacons. But due to performance reasons we should not update the tables 'aircraft_beacons' and 'receiver_beacons'. So we have to compute following things before:
receiver_id (FK to receivers)
device_id (FK to devices)
location_mgrs (location in MGRS format)
location_mgrs_short (location in short MGRS format for melissa stats)
distance (... to receiver)
radial (... to receiver)
quality (normalized signal quality)
...

The bulk import does it this way:
1. Import log data, convert it to csv and make a SQL COPY into a temporary table
2. Update temporary table (merge beacons)
3. Update receivers and devices
4. Insert temporary table into aircraft_beacons and receiver_beacons (todo: SQL UPSERT)
--> Very fast for big data

The continous import does it this way:
1. Cache the data in a dict (merge beacons)
2. Insert data into aircraft_beacons and receiver_beacons with SQL UPSERT
3. Updating of aircraft_beacons, receiver_beacons, receivers and devices afterwards (bad!)

What we need: something fast for big data AND for continuous data:
--> separate the workflow into:
A) Import data into DB (must work with multiple processes)
A1. Fill temporary table from file the fast way (SQL COPY)
or
A2. Fill temporary table from continuous data with SQL UPSERT

B) Prepare imported data, create missing receivers and devices

C) Import prepared date into aircraft_beacons and receiver_beacons
